### ISSUE TITLE
Error on remapping when install seadrop using foundry

### ISSUE THREAD

**Issue by Rizary** [ProjectOpenSea/seadrop#101]
Hi, 

I install this repo using `forge install` but when I try to flatten my file, I got strange error (see pic). And then I try to check the remappings but I got different remappings from `forge` and remappings.txt from seadrop.

I'll open another issue to forge, it might be forge issue, but it doesn't happened with other project that use foundry's remappings.

![image](https://github.com/ProjectOpenSea/seadrop/assets/7221768/6c71446b-355e-454a-a320-254a1e4ec1cf)

**Comment by ryanio** [comment]
Closing due to staleness, please open a new issue if you are still having issues

**Comment by Rizary** [comment]
@ryanio bro, what's completed? Have you fixed this already?
