### ISSUE TITLE
setMaxSupply missing checks!

### ISSUE THREAD

**Issue by decapinator** [ProjectOpenSea/seadrop#118]
ERC721A:

```
if(newMaxSupply < _totalMinted()){
     revert NewMaxSupplyLessThanTotalMinted(newMaxSupply);
  }
```

ERC1155:

```
 if(newMaxSupply < _tokenSupply[tokenid].totalMinted){ // or _tokenSupply[tokenid].totalSupply
      revert NewMaxSupplyLessThanTotalMinted(newMaxSupply);
 }
```

I guess those are require checks

**Comment by decapinator** [comment]
setMaxSupply function in contractMetadata accept newMaxSupply which can be less then current minted amount .. 

if the totalminted amount is 5000 , i can set the newMaxsupply to 2000 .. maybe it won't affect anything .. but why would u let the owner set it.

**Comment by decapinator** [comment]
i would fix it like this :

```
if(newMaxSupply < _totalMinted()) {
    revert CannotBeLessThenTotalMinted();
 }
```
or 

```
 if(newMaxSupply < _totalMinted()) {
      newMaxSupply = _totalMinted();
  }
```

**Comment by ryanio** [comment]
good call, thanks!
added:

v1: https://github.com/ProjectOpenSea/seadrop/commit/f08a0e703d6754db4ce51f9f57fa327234cf7aeb
v2: https://github.com/ProjectOpenSea/seadrop/commit/fe0d47a8ebcb8bf7efc475d76d8f37225760f4db
