### ISSUE TITLE
dead code

### ISSUE THREAD

**Issue by decapinator** [ProjectOpenSea/seadrop#123]
error InvalidSignedPaymentToken(address got, address want);
error InvalidSignedMintPrice(
        address paymentToken,
        uint256 got,
        uint256 minimum
    );
error InvalidSignedMaxTotalMintableByWallet(uint256 got, uint256 maximum);
error InvalidSignedMaxTotalMintableByWalletPerToken(
        uint256 got,
        uint256 maximum
    );
error InvalidSignedFromTokenId(uint256 got, uint256 minimum);
error InvalidSignedToTokenId(uint256 got, uint256 maximum);
error InvalidSignedStartTime(uint256 got, uint256 minimum);
error InvalidSignedEndTime(uint256 got, uint256 maximum);
error InvalidSignedMaxTokenSupplyForStage(uint256 got, uint256 maximum);
error InvalidSignedFeeBps(uint256 got, uint256 minimumOrMaximum);

**Comment by ryanio** [comment]
Thanks! Will remove.

**Comment by ryanio** [comment]
done, thanks!
