### ISSUE TITLE
Upgradable contract issue

### ISSUE THREAD

**Issue by opensea712** [ProjectOpenSea/seadrop#124]
Hello, I would like to deploy an upgradeable contract but I am getting this error.

```
Downloading compiler 0.8.17
DeclarationError: Identifier not found or not unique.
  --> src/lib/ERC721AConduitPreapprovedUpgradeable.sol:19:16:
   |
19 |     ) internal onlyInitializing {
   |                ^^^^^^^^^^^^^^^^


Error HH600: Compilation failed

For more info go to https://hardhat.org/HH600 or run Hardhat with --show-stack-traces
```

Besides, I don't understand what address "0x4468A5B725E2C63056131121cD33b66848E1dd87" is in `scripts/deploy.ts`.
(Related article: https://forum.openzeppelin.com/t/deploy-proxy-parameters/38707)

Thank you for your consideration.

**Comment by opensea712** [comment]
By the way, are there any deployed contracts inheriting this upgradable contract? If yes, can you please share them?

I am still not sure how I can use this for my contract.

**Comment by ryanio** [comment]
@opensea712 thanks, this should be fixed now if you want to pull the main branch.

> By the way, are there any deployed contracts inheriting this upgradable contract? If yes, can you please share them?

Yes people are using this, I'd have to remember which projects though.
You can look at `ExampleToken.sol` in `src-upgradeable` as an example that inherits and modifies.
