### ISSUE TITLE
Provenancehash when supply change

### ISSUE THREAD

**Issue by dcapitator** [ProjectOpenSea/seadrop#128]
How are u handling the provenancehash update if mint started and supply inflated or got reduced to totalMinted() and then inflated with new tokens metadata ?

three different ways to reproduce it :

-Mint is done and creator adds more supply >> no more provenancehash updates

-Mint started but the creator decided to reduce the supply for now from 5000 tokens to 4000 tokens , then later he inflate it to
7000 with new tokens

-Mint started and the collections mints out . Then later creator decided to add more supply ( kind of seasonal mints )

**Comment by dcapitator** [comment]
@ryanio

**Comment by ryanio** [comment]
changes like that are not supported, provenance hash is meant to be as close to immutable as possible. if changes to metadata are made that don't match the provenance hash they can be communicated to the community separately, as it's just an informational endpoint

**Comment by dcapitator** [comment]
so it works only for the first batch if maxSupply is not updated right ? 

I tried to find a way to keep it publically unchanged but still fit in this scenario were i have seasonal drop by inflating supply and i couldnt implement any way to achieve . So i have no choice other then removing the provenance hash or allow the change with events and off-chain proof.
