### ISSUE TITLE
How to deploy ERC-1155 contract?

### ISSUE THREAD

**Issue by AnhDOS** [ProjectOpenSea/seadrop#43]
Hi,

Is there any document to deploy ERC-1155 contract?

**Comment by ryanio** [comment]
We do not have an ERC-1155 SeaDrop token contract yet but we are planning to! Check back soon.

**Comment by AnhDOS** [comment]
Well. We have to wait then.

**Comment by claritise** [comment]
> We do not have an ERC-1155 SeaDrop token contract yet but we are planning to! Check back soon.

Do you guys have a rough time estimate of when you guys plan to drop it? We are planning a ERC1155 drop and would love to be able to use a SeaDrop integration.

**Comment by claritise** [comment]
> We do not have an ERC-1155 SeaDrop token contract yet but we are planning to! Check back soon.

We are planning on launching a ERC1155 drop in 1 months time and would love to be able to use SeaDrop. Do you guys reckon we would have access to it in that time-frame or should we look for alternatives?

**Comment by ryanio** [comment]
It will not be ready in 2 weeks from now sorry, but we are working on it!

**Comment by ryanio** [comment]
ERC-1155 is now available in `v2` branch, OpenSea selfserve UI will be adding it in the coming months
