### ISSUE TITLE
Unable to run yarn build

### ISSUE THREAD

**Issue by piedup** [ProjectOpenSea/seadrop#59]
Tried on both master and seadrop-1.0. I get the same error:
```
Error HH404: File lib/ERC721A/contracts/ERC721A.sol, imported from src/ERC721ContractMetadata.sol, not found.
```

**Comment by sreyemnayr** [comment]
You have to pull the submodules. The simplest way is by using the `--recurse-submodules` flag as stated in the README:
```bash
git clone --recurse-submodules https://github.com/ProjectOpenSea/seadrop && cd seadrop
```
Otherwise you can also use `git submodule init && git submodule update` after the fact

**Comment by piedup** [comment]
Thank you!
