### ISSUE TITLE
Deploying upgradeable ERC721SeaDrop using the official steps has breaking issues

### ISSUE THREAD

**Issue by claritise** [ProjectOpenSea/seadrop#67]
I have followed the exact steps as listed in https://github.com/ProjectOpenSea/seadrop/tree/main/src-upgradeable#readme to deploy an upgradeable seadrop contract, using the `ExampleToken` contract.

However once deployed it does get indexed as a collection on opensea but when attempting the drop the collection I would get an error in opensea as follows:

![image](https://user-images.githubusercontent.com/20750968/234756024-3eb07a16-981e-493d-9037-580ced0b363b.png)

![image](https://user-images.githubusercontent.com/20750968/234755684-783fb835-4264-4500-b4df-4522a4f5f710.png)

This is using a fresh copy of the most recent commit, having tried on multiple wallets and networks. This issue does not occur when deploying a contract from the opensea UI using the web interface but only when deploying a contract using hardhat. 

We are currently blocked from launching a drop so any help would be greatly appreciated 🙏🏻

**Comment by ryanio** [comment]
Hi @claritise really sorry for the delay just seeing this.

The error you are encountering based on your screenshot `0x59d97937` using https://openchain.xyz/signatures?query=0x59d97937 results to `OnlyOwnerOrAdministrator()`. Were you using the latest commit after https://github.com/ProjectOpenSea/seadrop/commit/2f6e4d7a2f7ab53916c8f82374d944e8de74079a? It should have been fixed there. Would also recommend not using the partner contracts and just the normal ones, as it only restricts functionality when not needed when using the OpenSea UI.
