### ISSUE TITLE
Add IERC721AQueryable extension

### ISSUE THREAD

**Issue by alexbakers** [ProjectOpenSea/seadrop#73]
Hello,

Please add IERC721AQueryable extension

https://github.com/chiru-labs/ERC721A/blob/c66792253580acb2b7a873046858175d213e5b65/contracts/extensions/ERC721AQueryable.sol

Thx.

**Comment by ryanio** [comment]
If you want to use that extension you can fork your own ERC721SeaDrop and replace ERC721A with ERC721AQueryable, it should not cause any issues with SeaDrop compatibility.
