### ISSUE TITLE
Is ERC721SeaDropUpgradeable Supported?

### ISSUE THREAD

**Issue by Buooy** [ProjectOpenSea/seadrop#82]
Wanted to clarify if upgradeable contracts are supported? Having tried it out for a few days, I have noticed the following challenges that I do not encounter with the non-upgradeable version.

Note that I am on the main branch

1. @openzeppelin/hardhat-upgrades is not included in package.json but utilised in hardhat.config.ts 
2. Custom Unrecognised Error encountered when attempting to mint on a locally forked Mumbai hardhat env and/or deploy a local instance of SeaDrop
3. Deployment of ERC721SeaDropUpgradeable contract leads to a "Large Contract Size" error and requires `allowUnlimitedContractSize: true` to be included hardhat.config.ts
4. No valid tests within `src-upgradeable`

Wanted to check with the team if the upgradeable contract is tested, supported and if there have been any cases where an upgradeable ERC721SeaDrop contract has been deployed and minted successfully.

**Comment by ryanio** [comment]
yes it does work, there are many deployments of it out in the wild. instructions [here](https://github.com/ProjectOpenSea/seadrop/tree/main/src-upgradeable#deployment).

not sure why you're having issues with the contract size, haven't seen that before.

i haven't gotten a chance to hook it up to the existing test suite, i will do for v2 which we'll be upgrading to over the next weeks/months and I have yet to build out upgradeable contracts for those yet, when I do it will definitely be hooked up the to the test suite.

**Comment by Buooy** [comment]
thanks for the fast response. to be fair, im using a local fork of mumbai and haven't tried deploying it to testnet directly. 

i'll give that a shot and see if there are any issues and revert back if i do

**Comment by Buooy** [comment]
Hi, wanted to do a quick confirmation that it deploys well on sepolia testnet and I could do a full end to end flow.  
  
However for some reason, it doesn't work properly if you fork a network on hardhat or if you deploy on a local hardhat node.  
  
As such, there isn't a way to unit test the upgradeable contracts.  
  
Looking forward to the v2 update. happy to help as well.  
  
Will close this issue. thanks @ryanio for ur response
