### ISSUE TITLE
safeTransferFrom isn't virtual.

### ISSUE THREAD

**Issue by zendevil** [ProjectOpenSea/seadrop#87]
I want to change the functionality of ```safeTransferFrom``` to run some code that changes the NFT's on-chain stored data. But both the ```safeTransferFrom```s aren't virtual and making them virtual in order to override the function in an inherited contract breaks the minting functionality on OpenSea website. Changing the function body itself and deploying ERC721SeaDrop also breaks the minting functionality.

**Comment by ryanio** [comment]
making it virtual shouldn't break the minting functionality on OpenSea if you don't interfere with the original functionality of safeTransferFrom, can you give an example of what you are trying to do?

**Comment by zendevil** [comment]
I changed     
```
function safeTransferFrom(
        address from,
        address to,
        uint256 tokenId
    ) public override onlyAllowedOperator(from) {
        super.safeTransferFrom(from, to, tokenId);
    }
```
to 
```
    function safeTransferFrom(
        address from,
        address to,
        uint256 tokenId
    ) public override virtual onlyAllowedOperator(from) {
        super.safeTransferFrom(from, to, tokenId);
    }

```
and the Minting now page disappears.

**Comment by ryanio** [comment]
that should be fine. after you deploy the token, you should see it appear on opensea.io/studio and you can click `View drop page` then `Edit drop`. "Minting now" won't show on the collection page unless the drop is actively minting after configuration

**Comment by zendevil** [comment]
<img width="1435" alt="Screenshot 2023-10-12 at 3 40 56 PM" src="https://github.com/ProjectOpenSea/seadrop/assets/30054030/e2a3d8ec-e62a-4ae7-876c-28fb203f397e">
But the mint is not showing up when I add _runGameOfLife to ERC721SeaDrop like it shows here when it isn't added, plus the three minted NFTs aren't shown either.
<img width="1435" alt="Screenshot 2023-10-12 at 3 44 28 PM" src="https://github.com/ProjectOpenSea/seadrop/assets/30054030/cdbc8f79-a363-40f9-ab66-670430d5b30a">
And the changed contract is showing as an ERC1155 on the studio page.

**Comment by ryanio** [comment]
unless you share the actual verified contracts and addresses it's difficult for me to help you further
