### ISSUE TITLE
Creator earnings aren't enforced with the ExampleToken script

### ISSUE THREAD

**Issue by zendevil** [ProjectOpenSea/seadrop#88]
I'm using the ```DeployAndConfigureExampleToken.s.sol``` to deploy my contract on the sepolia testnet. The script has the following lines, which I think are supposed to enforce royalty.
```
uint16 feeBps = 500; // 5%
        token.updatePublicDrop(
            seadrop,
            PublicDrop(
                mintPrice,
                uint48(block.timestamp), // start time
                uint48(block.timestamp) + 1000, // end time
                maxTotalMintableByWallet,
                feeBps,
                true
            )
        );
```
But in the drop settings, I seed that earnings are optional for this collection. I want to make the earnings enforced at 5% according to the script. How can I make that happen?
<img width="806" alt="Screenshot 2023-10-13 at 12 00 01 PM" src="https://github.com/ProjectOpenSea/seadrop/assets/30054030/1f65a2cf-0a80-4dd7-8682-8406ccaa0c26">

**Comment by thenerdassassin** [comment]
Creator Earnings will be optional for all new collections.

https://x.com/opensea/status/1692224333551186379?s=20

**Comment by zendevil** [comment]
<img width="876" alt="Screenshot 2023-10-13 at 12 16 40 PM" src="https://github.com/ProjectOpenSea/seadrop/assets/30054030/1a47d96a-a941-4d9f-8ffe-0df9b137987c">
Here it says the earnings can be enforced or optional.
