### ISSUE TITLE
How to enforce creator earnings on seadrop contract?

### ISSUE THREAD

**Issue by zendevil** [ProjectOpenSea/seadrop#89]
My seadrop deployment is showing all tokens without royalty paid to the creator.

https://github.com/ProjectOpenSea/seadrop/assets/30054030/5b16c01b-e80d-4a54-9f34-b9369a4342a1

How do I make it so that the sale of an NFT always pays 5% to the creator?

**Comment by zendevil** [comment]
<img width="913" alt="Screenshot 2023-10-13 at 12 57 08 PM" src="https://github.com/ProjectOpenSea/seadrop/assets/30054030/c1b45672-c0de-47e6-b500-97fa3894d251">
The royalty also shows up as optional whereas seadrop does implement royaltyInfo. I want to make it so that it is enforced. How do I do that?

**Comment by ryanio** [comment]
seadrop has no secondary royalty enforcement mechanism, the token simply provides ERC-2981 

creator earnings are only optional and can no longer be enforced on OpenSea for new collections. see the announcement here: https://opensea.io/blog/articles/creator-fees-update

also, please stop opening issues and instead use [discussions](https://github.com/ProjectOpenSea/seadrop/discussions)
